### ISSUE TITLE
Don't act on shortcuts when an input is focused

### ISSUE THREAD

**Issue by knyghty** [knyghty/django-admin-keyboard-shortcuts#13]
Or something.

Currently any shortcuts can be handled when typing text into an input. This is very annoying and can navigate you to a different page, e.g. if you press `g` followed by `i`.

**Comment by eviljeff** [comment]
Documenting my investigation into using aria role to identify text fields [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role]: tl;dr, it's not possible.

Aria roles are not exposed in the DOM to javascript, and although there is a [plan](https://wicg.github.io/aom/) to expose accessibility data to the DOM it doesn't appear to be heading to implementation fast - most of the discussions I found started 10 years ago.  Firefox and Chromium have some partial support, but both disabled behind a [config flag](https://chromestatus.com/feature/5530552681627648) - which are also not heading to being enabled by default any time soon, [looks like](https://issues.chromium.org/issues/41148611#comment2).

I _thought_ aria roles were more exposed because [testing-library](https://testing-library.com/docs/queries/byrole/) allows them to be referenced, but tracing through the testing-library source code eventually leads to hard-coded definitions in [aria-query](https://github.com/A11yance/aria-query/blob/v5.3.0/src/etc/roles/literal/textboxRole.js). 

Adding aria-query as a dependency doesn't seem justifiable to me, and with no browser support on the horizon I think we're limited to checking tag names and input `type`.

**Comment by knyghty** [comment]
Makes sense to me. I also added this in the PR, but belongs here: I think we should also only disable what I'm going to call "raw" shortcuts - those without a modifier. So the alt+something shortcuts should still work.

Still need to think about how this all works if people use alt in a text box to create fancier letters, though.
